# Generated by Django 5.2 on 2025-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('dep', models.TextField(max_length=30, null=True)),
                ('birthdate', models.CharField(max_length=30, null=True)),
                ('salary', models.TextField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, null=True, unique=True)),
                ('timein', models.DateTimeField(blank=True, null=True)),
                ('timeout', models.DateTimeField(blank=True, null=True)),
                ('company', models.CharField(choices=[('company 1', 'company 1'), ('company 2', 'company 2')], max_length=20, null=True)),
            ],
        ),
    ]
