# Generated by Django 5.1.6 on 2025-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_review_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='shop',
            field=models.CharField(choices=[('skaitech', 'skaitech'), ('3dskai', '3dskai')], max_length=20, null=True),
        ),
    ]
