# Generated by Django 5.1.6 on 2025-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumbsDownCount',
        ),
        migrations.RemoveField(
            model_name='review',
            name='thumbsUppCount',
        ),
        migrations.AddField(
            model_name='review',
            name='thumbsDownAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbsUppAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
